# Generated by Django 2.2.6 on 2020-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre clase')),
                ('publica', models.BooleanField(default=True, help_text='Determina si la clase estará pública para estudiantes y voluntarias', verbose_name='clase publica')),
                ('fecha_clase', models.DateField(help_text='Fecha en la que se realizará la clase', verbose_name='fecha clase')),
            ],
            options={
                'ordering': ['fecha_clase'],
            },
        ),
    ]
