# Generated by Django 2.0.13 on 2020-01-29 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='clase_default', max_length=100, verbose_name='nombre clase')),
                ('publica', models.BooleanField(default=True, verbose_name='clase publica')),
                ('fecha_clase', models.DateField(default=datetime.date.today, verbose_name='fecha clase')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='problemas',
            field=models.ManyToManyField(blank=True, related_name='profesoras', to='clases.Problema'),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('nombre', 'curso')},
        ),
    ]
    