# Generated by Django 2.0.13 on 2020-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20200106_1331'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='clase_default', max_length=100, verbose_name='nombre clase'),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('nombre', 'curso')},
        ),
    ]
