# Generated by Django 2.2.6 on 2019-11-18 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha clase'),
        ),
    ]
