# Generated by Django 2.1.15 on 2020-01-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_cant_clases'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='clase_default', max_length=100, verbose_name='nombre clase'),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('nombre', 'curso')},
        ),
    ]
