# Generated by Django 2.2.6 on 2020-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20200504_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='problemas',
            field=models.ManyToManyField(blank=True, help_text='Problemas a resolver en esta clase', to='problemas.Problema'),
        ),
    ]
