# Generated by Django 2.2.13 on 2020-06-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20200605_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='problemas',
        ),
    ]
