# Generated by Django 2.2.13 on 2020-06-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_clase_problemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='problemas',
        ),
    ]
