# Generated by Django 2.2.6 on 2020-05-06 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problemas', '0002_caso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se recibe el feedback')),
                ('codigo_solucion', models.FileField(help_text='Se acepta formato .cpp', upload_to='soluciones', validators=[django.core.validators.FileExtensionValidator(['cpp'])])),
                ('problema', models.ForeignKey(help_text='Problema asociado al feedback', on_delete=django.db.models.deletion.CASCADE, to='problemas.Problema')),
                ('user', models.ForeignKey(help_text='Usuaria dueña del feedback.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(help_text='Si el test paso o no')),
                ('output_obtenido', models.CharField(help_text='Output obtenido para el test', max_length=255)),
                ('error', models.CharField(max_length=500)),
                ('caso', models.ForeignKey(help_text='Caso que probó este test_feedback', on_delete=django.db.models.deletion.CASCADE, to='problemas.Caso')),
                ('feedback', models.ForeignKey(help_text='Feedback con que se creó este test_feedback', on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
            ],
        ),
    ]
