# Generated by Django 2.2.6 on 2020-05-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0003_auto_20200518_1218'),
        ('feedback', '0002_output_alternativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='output_alternativo',
            new_name='OutputAlternativo',
        ),
    ]
