# Generated by Django 2.2.6 on 2020-05-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_outputalternativo_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfeedback',
            name='output_alternativo',
            field=models.ForeignKey(blank=True, help_text='si existe una sugerencia para el output obtenido,se agrega aquí', null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.OutputAlternativo'),
        ),
    ]
