# Generated by Django 2.2.13 on 2020-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_testfeedback_output_alternativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resultado',
            field=models.BooleanField(default=True, help_text='Si paso todos los test o no'),
        ),
    ]
