# Generated by Django 2.0.13 on 2020-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cant_clases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
