# Generated by Django 2.2.6 on 2020-05-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cant_clases',
            field=models.IntegerField(default=1),
        ),
    ]
