# Generated by Django 2.1.15 on 2020-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20200106_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cant_clases',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
