# Generated by Django 2.2.6 on 2019-10-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20191017_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default='curso_default', max_length=100, unique=True),
        ),
    ]
