# Generated by Django 2.2.6 on 2020-06-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20200502_0315'),
        ('cursos', '0002_auto_20200504_2018'),
    ]

    operations = [
    ]
