# Generated by Django 2.2.6 on 2020-05-04 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clases', '0002_auto_20200504_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='alumna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Clase'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumna', 'clase')},
        ),
    ]
