# Generated by Django 2.2.6 on 2020-05-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='author',
        ),
        migrations.DeleteModel(
            name='Asistentes',
        ),
    ]
