# Generated by Django 2.0.13 on 2020-01-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
        ('cursos', '0002_auto_20200106_1331'),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_clase',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Clase'),
        ),
        migrations.AddField(
            model_name='asistencia_clase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
    ]
