# Generated by Django 2.0.13 on 2020-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_auto_20200109_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistio',
            field=models.BooleanField(default=True, verbose_name='alumna asisitio'),
            preserve_default=False,
        ),
    ]
