# Generated by Django 2.1.15 on 2020-01-14 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clases', '0001_initial'),
        ('asistencia', '0004_asistencia_asistio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumna', 'clase')},
        ),
    ]
