# Generated by Django 2.2.5 on 2019-09-27 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_profesora', models.BooleanField(default=False, verbose_name='estado de profesora')),
                ('es_voluntaria', models.BooleanField(default=False, verbose_name='estado de voluntaria')),
                ('es_coordinadora', models.BooleanField(default=False, verbose_name='estado de coordinadora')),
                ('es_alumna', models.BooleanField(default=False, verbose_name='estado de alumna')),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media/imagenes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
