# Generated by Django 2.2.6 on 2020-05-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='users'),
        ),
    ]
