# Generated by Django 2.2.6 on 2020-05-04 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('statement', models.FileField(help_text="Solo se aceptan PDF's", upload_to='statements', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('source', models.FileField(blank=True, null=True, upload_to='source')),
                ('tests', models.FileField(help_text='Se aceptan formatos .csv y .json', upload_to='test_files', validators=[django.core.validators.FileExtensionValidator(['json', 'csv'])])),
            ],
        ),
    ]
