# Generated by Django 2.2.6 on 2020-05-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción del caso')),
                ('input', models.CharField(help_text='Input del caso', max_length=255)),
                ('output_esperado', models.CharField(help_text='Output esperado para el input', max_length=255)),
                ('problema', models.ForeignKey(help_text='Problema al que pertenece el caso', on_delete=django.db.models.deletion.CASCADE, to='problemas.Problema')),
            ],
        ),
    ]
