# Generated by Django 2.2.6 on 2020-05-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0003_auto_20200518_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='clases',
            field=models.CharField(default='{"clases": []}', help_text='json con la lista de clases a las que pertenece el problema', max_length=255),
        ),
    ]
