# Generated by Django 2.2.13 on 2020-06-09 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_remove_clase_problemas'),
        ('problemas', '0007_remove_problema_clases'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='clases',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clases.Clase'),
            preserve_default=False,
        ),
    ]
