# Generated by Django 2.2.13 on 2020-06-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0009_auto_20200609_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='clases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.Clase'),
        ),
    ]
