# Generated by Django 2.2.13 on 2020-06-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0010_auto_20200609_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problema',
            old_name='clases',
            new_name='clase',
        ),
    ]
