# Generated by Django 2.2.13 on 2021-01-06 17:35

import django.core.validators
from django.db import migrations, models
import my_lib.files_wrapper


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0011_auto_20200609_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='tests',
            field=models.FileField(help_text='Se aceptan formatos .csv y .json', upload_to='test_files', validators=[django.core.validators.FileExtensionValidator(['json', 'csv']), my_lib.files_wrapper.check_if_file_is_valid]),
        ),
    ]
